build: # build chrome extension
	@npm ci
	@npm run build

dev: # run tasks for development
	@npm run dev

test: # run tests
	@npm run dev:test

clean: # clean generated resources
	@npm run clean

profile: # view bundle profile
	@npm run profile
